version: '3'

networks:
    loki:

volumes:
    eslogs01:
    eslogs02:
    esdata01:
        driver: local
    esdata02:
        driver: local

services:
    loki:
        image: 'grafana/loki:master'
        ports:
            - '3100:3100'
        command: '-config.file=/etc/loki/local-config.yaml'
        networks:
            - loki
    grafana:
        image: 'grafana/grafana:latest'
        ports:
            - '3000:3000'
        networks:
            - loki
    es01:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.4.1'
        container_name: es01
        environment:
            - node.name=es01
            - discovery.seed_hosts=es02
            - 'cluster.initial_master_nodes=es01,es02'
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock: {soft: -1, hard: -1}
        volumes:
            - '/Users/dzhdanov/git/deniszh/loki-sidecar-test/es-log4j2.properties:/usr/share/elasticsearch//config/log4j2.properties'
            - 'esdata01:/usr/share/elasticsearch/data'
            - 'eslogs01:/usr/share/elasticsearch/logs'
        ports:
            - '9200:9200'
        networks:
            - loki
    promtail01:
        image: 'grafana/promtail:master'
        volumes:
            - '/Users/dzhdanov/git/deniszh/loki-sidecar-test/promtail01.yaml:/etc/promtail/docker-config.yaml'
            - 'eslogs01:/var/log/elasticsearch'
        command: '-config.file=/etc/promtail/docker-config.yaml'
        networks:
            - loki
    es02:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.4.1'
        container_name: es02
        environment:
            - node.name=es02
            - discovery.seed_hosts=es01
            - 'cluster.initial_master_nodes=es01,es02'
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock: {soft: -1, hard: -1}
        volumes:
            - '/Users/dzhdanov/git/deniszh/loki-sidecar-test/es-log4j2.properties:/usr/share/elasticsearch//config/log4j2.properties'
            - 'esdata02:/usr/share/elasticsearch/data'
            - 'eslogs02:/usr/share/elasticsearch/logs'
        networks:
            - loki
    promtail02:
        image: 'grafana/promtail:master'
        volumes:
            - '/Users/dzhdanov/git/deniszh/loki-sidecar-test/promtail02.yaml:/etc/promtail/docker-config.yaml'
            - 'eslogs02:/var/log/elasticsearch'
        command: '-config.file=/etc/promtail/docker-config.yaml'
        networks:
            - loki

